version: "3.8"

networks:
  ft_transcendence:
    driver: bridge

volumes:
  db:
    driver: local
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: .temp/postgres

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - "db:/var/lib/postgresql/data:z"
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - ft_transcendence
    env_file:
      - requirements/.env

  web:
    image: web
    container_name: web
    tty: true
    build:
      context: requirements
    ports:
      - '8000:8000'
    env_file:
      - requirements/.env
    volumes:
      - ./requirements/main:/main
    restart: unless-stopped
    networks:
      - ft_transcendence
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -q -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["bash", "/chat/start.sh"]

  nginx:
    build:
      context: requirements/nginx
    restart: unless-stopped
    volumes:
      - ./requirements/main:/main
    networks:
      - ft_transcendence
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - requirements/.env
    volumes:
      - ./.temp/redis:/data
    networks:
      - ft_transcendence
