# Generated by Django 5.0.2 on 2024-03-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
    ]
